### PR TITLE
Avoid UnicodeEncodeError if a path contains invalid characters

### PR DESCRIPTION
**Pull request by hvelarde**

### CODE REVIEW

**Comment by sunew** [comment]
plone.app.transmogrifier/src/plone/app/transmogrifier/pathfixer.py would be a good place to ensure the path is ascii

**Comment by hvelarde** [comment]
I saw it, but I have no strong opinion on that; let's wait for some other comments.

`plone.app.transmogrifier.pathfixer` seems to address a different use case.

**Comment by sunew** [comment]
but you must be hit by the same problem in other parts of your pipeline? Or you have a special case?
pathfixer is typically for stripping the plone site id from a plone export. (Or adding / removing other pre/postfixes).
I think it could be quite natural for this case also, now the path is already being processed and added back to the pipeline item.

**Comment by hvelarde** [comment]
@sunew done!

@jsbueno do you mind to implement your solution on a different pull request to allow others review it?

**Comment by sunew** [comment]
@hvelarde LGTM :)

**Comment by hvelarde** [comment]
@sunew do you mind to approve it then?

**Comment by sunew** [comment]
@hvelarde I no longer had the button to approve, after i reviewed with a comment... Strange. I had to readd myself as a reviewer.

**Comment by hvelarde** [comment]
@sunew you have to go to the Files changed tab and then review again ;)

**Comment by sunew** [comment]
@hvelarde :) I approved - you can merge

**Comment by hvelarde** [comment]
thanks! I prefer to wait for others to review this also :)

**Comment by erral** [comment]
I tried to fix this with some encoding/decoding stuff somewhere because paths were unicode characters instead of strings in some cases, I don't recall it where...

Anyway, it looks good to me.

**Comment by erral** [comment]
I found it: https://github.com/collective/collective.jsonmigrator/pull/21

**Pull request merged**
