### PR TITLE
Uses Github Actions to CI

### PR DESCRIPTION
**Pull request by wesleybl**

### CODE REVIEW

**Comment by wesleybl** [comment]
Can someone please remove Travis from this repository? It's still being required.

Or can someone put me as owner?

@gotcha @thet @mauritsvanrees @jensens

**Review by mauritsvanrees — APPROVED** [review]
LGTM.

I have removed the travis web hook. I hope that is enough.

**Comment by wesleybl** [comment]
Thanks @mauritsvanrees ! I intend to make this package compatible with Plone 5.2 and Python 3.

**Comment by mauritsvanrees** [comment]
That sounds good.
Personally, I would go with collective.exportimport these days.
But if you are already used to transmogrifier, then that is definitely more battle tested.

**Comment by jensens** [comment]
Be aware there is already an old python3 branch by @cdw9 - that said, I have no idea whats the state of this branch nor  did I had a deeper look at it.

**Comment by cdw9** [comment]
@zopyx also had some commits on that branch. I had committed some code just for the pieces that I needed to work. I'm sure there is more that needs to be updated, plus we'll need to make sure the tests pass. I never got to working on it more to do these tasks, which is why it never got merged.

**Comment by wesleybl** [comment]
I created a new branch but I'm going to take a look at the other banch. Thank you for the warning!

**Pull request merged**
